export const prefs = [
    'Responds well to visual imagery',
     'Seeks clear guidance',
      'Desires social interaction',
     'Thrives under motivation',
     'Benefits from stress management techniques',
     'Responds well to auditory cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'Benefits from social support',
     'Responds well to physical cues',
     'Seeks clear, concise communication',
     'Desires independence',
     'Thrives under stress',
     'likes puns',
     'Benefits from social support',
     'Appreciates thoughtful suggestions',
     
]